version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2023:2023'
    depends_on:
      - db
    networks:
      - ticket-booking-network

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=booking@123
      - POSTGRES_DB=bookings
    volumes:
      - ticket-booking-db:/var/lib/postgresql/data
    networks:
      - ticket-booking-network

networks:
  ticket-booking-network:

volumes:
  ticket-booking-db: